// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgB3K0IaSH-gInbQP1RgkDaAeXzuVg7rg',
    appId: '1:603516174250:web:608cd1f1c8557fac6d35d3',
    messagingSenderId: '603516174250',
    projectId: 'chatsetgo-flutter-app',
    authDomain: 'chatsetgo-flutter-app.firebaseapp.com',
    storageBucket: 'chatsetgo-flutter-app.firebasestorage.app',
    measurementId: 'G-8EGPK3J7SV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrNW_55hBDOaaKXNFG4u36zu1ompqsS54',
    appId: '1:603516174250:android:e0b63668381829066d35d3',
    messagingSenderId: '603516174250',
    projectId: 'chatsetgo-flutter-app',
    storageBucket: 'chatsetgo-flutter-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbG0nAR-IFDlm49IWKEmUzVy1YhBpej3k',
    appId: '1:603516174250:ios:2a2fe668e3965c1b6d35d3',
    messagingSenderId: '603516174250',
    projectId: 'chatsetgo-flutter-app',
    storageBucket: 'chatsetgo-flutter-app.firebasestorage.app',
    iosBundleId: 'com.chatsetgo.chatsetgo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbG0nAR-IFDlm49IWKEmUzVy1YhBpej3k',
    appId: '1:603516174250:ios:2a2fe668e3965c1b6d35d3',
    messagingSenderId: '603516174250',
    projectId: 'chatsetgo-flutter-app',
    storageBucket: 'chatsetgo-flutter-app.firebasestorage.app',
    iosBundleId: 'com.chatsetgo.chatsetgo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgB3K0IaSH-gInbQP1RgkDaAeXzuVg7rg',
    appId: '1:603516174250:web:be8dfeccc06ef2676d35d3',
    messagingSenderId: '603516174250',
    projectId: 'chatsetgo-flutter-app',
    authDomain: 'chatsetgo-flutter-app.firebaseapp.com',
    storageBucket: 'chatsetgo-flutter-app.firebasestorage.app',
    measurementId: 'G-86X8TSDL19',
  );
}
